// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsBaEt-u1Rzdmb9zYCkQP0HkoKMexL65k',
    appId: '1:169552984006:web:448578a6ebb461ca1a64c7',
    messagingSenderId: '169552984006',
    projectId: 'nextround-1f9b6',
    authDomain: 'nextround-1f9b6.firebaseapp.com',
    storageBucket: 'nextround-1f9b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBBE6rUsnooW9-hRFjwkbDvfsuvcIpuWo',
    appId: '1:169552984006:android:8835e327a82e0cce1a64c7',
    messagingSenderId: '169552984006',
    projectId: 'nextround-1f9b6',
    storageBucket: 'nextround-1f9b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1rgbw5L96mWBtUUBeFK6Hf2Oy3esDUL4',
    appId: '1:169552984006:ios:4ea7954f51fcd2491a64c7',
    messagingSenderId: '169552984006',
    projectId: 'nextround-1f9b6',
    storageBucket: 'nextround-1f9b6.appspot.com',
    iosClientId: '169552984006-guob2ku9c9oq6lqabpla831dh35k49kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1rgbw5L96mWBtUUBeFK6Hf2Oy3esDUL4',
    appId: '1:169552984006:ios:4ea7954f51fcd2491a64c7',
    messagingSenderId: '169552984006',
    projectId: 'nextround-1f9b6',
    storageBucket: 'nextround-1f9b6.appspot.com',
    iosClientId: '169552984006-guob2ku9c9oq6lqabpla831dh35k49kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp',
  );
}
